<a href="https://colab.research.google.com/github/jiku100/2020-2-machine-running-proejct/blob/master/assignment3/%EC%8B%A0%EC%84%9D%EA%B2%BD_assignment_03_a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulate PyTorch Tensors
<hr>

## Matrix manipulation

In [ ]:
import torch

### Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [ ]:

# write your code here

A = torch.tensor([[1.,2.],[3.,4.]])
B = torch.tensor([[10.,20.],[30.,40.]])
C = A + B

# print
print(A)
print('')
print(B)
print('')
print(C)

tensor([[1., 2.],
        [3., 4.]])

tensor([[10., 20.],
        [30., 40.]])

tensor([[11., 22.],
        [33., 44.]])


### Print the dimension, size and type of the matrix A. Remember, the commands are dim(), size() and type()

In [ ]:

# write your code here

print(A.dim())    # print the dimension of the matrix A
print('')
print(A.size())    # print the size of the matrix A
print('')
print(A.dtype)    # print the type of the matrix A

2

torch.Size([2, 2])

torch.float32


### Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted.

In [ ]:

# write your code here

A_long = A.long()

print(A_long.dtype)    # print the type of A_long
print('')
print(A.dtype)    # print the type of A

torch.int64

torch.float32


### Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following:   1) Print the tensor,  2) Print its type, 3) Print its dimension,  4) Print its size, 5) Print the size of its middle dimension.

In [ ]:

# write your code here

A = torch.rand(5, 2, 3)

print(A)
print(A.dtype)    # print the type of A
print(A.dim())    # print the dimension of A
print(A.size())    # print the size of A
print(A.size()[1])    # print the size of the middle (second) dimension

tensor([[[0.4679, 0.9255, 0.2345],
         [0.7901, 0.5932, 0.4890]],

        [[0.8673, 0.2743, 0.3380],
         [0.4803, 0.4979, 0.5206]],

        [[0.0201, 0.8772, 0.8262],
         [0.4346, 0.5516, 0.0641]],

        [[0.7839, 0.0737, 0.1642],
         [0.0246, 0.2567, 0.0396]],

        [[0.2179, 0.5114, 0.4571],
         [0.6231, 0.5645, 0.0715]]])
torch.float32
3
torch.Size([5, 2, 3])
2


### Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display.

In [ ]:

# write your code here

A = torch.zeros(2,3,4,5)

print(A)


tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])
